name: "Continuous Integration"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: create .env
        env:
          MNEMONIC_SECRET: ${{ secrets.MNEMONIC_SECRET }}
          MNEMONIC_ENC: ${{ secrets.MNEMONIC_ENC }}
        run: |
          touch .env
          echo MNEMONIC_SECRET=$MNEMONIC_SECRET >> .env
          echo MNEMONIC_ENC=$MNEMONIC_ENC >> .env
        shell: bash

      - run: yarn install
      - run: yarn build
      - run: yarn lint:all
      - run: yarn coverage # runs tests as well

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.json
#          flags: unittests
#          name: codecov-umbrella
#          fail_ci_if_error: true
