name: "Continuous Integration"

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn coverage # runs tests as well

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.json
#          flags: unittests
#          name: codecov-umbrella
#          fail_ci_if_error: true
